NAME = ft_printf.a
CC = cc
CFLAGS = -Wall -Wextra -Werror

SRC = ft_print.c\
	  ft_print_char.c
OBJ = $(SRC:.c=.o)


all: $(NAME)

$(NAME): $(OBJ)
	ar rcs $(NAME) $(OBJ)
	
clean: 
	rm -f $(OBJ) $(BONUS_OBJ)

fclean :clean 
	rm -f $(NAME)

re: fclean all 
.PHONY: all clean fclean re bonus